version: 0.2
env:
  variables:
    BUILD_FOLDER: dist/NG-Grid

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install dependencies needed for running tests
      - npm install --save ag-grid-angular ag-grid-community xlsx ag-grid-enterprise
      - npm install -g @angular/cli 
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - npm run test
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - ng build
      - rm -dfr node_modules
      - aws s3 cp --recursive $BUILD_FOLDER s3://$WEBSITE_S3_BUCKET/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - sed -i -e "8 s|href=\"|&$WEBSITE_S3_PREFIX/|g" $BUILD_FOLDER/index.html
      - sed -i -e "11 s|href=\"|&$WEBSITE_S3_PREFIX/|g" $BUILD_FOLDER/index.html 
      - sed -i -e "18 s|src=\"|&$WEBSITE_S3_PREFIX/|g" $BUILD_FOLDER/index.html 
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
    - template-export.yml
    - template-configuration.json
  #  - "**/*"
  #discard-paths: no
  #base-directory: $BUILD_FOLDER